name: frontend branch build test

on:
  pull_request:
    paths:
    - 'client/**'
    branches: ["frontend"]
  
jobs:
  build-test:
    name: client-pr-test
    runs-on: ubuntu-20.04
    defaults:
      run: 
        working-directory: ./client
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build