# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    paths:
     - 'server/**'
    branches: ["dev"]

permissions:
  contents: read
  
env:
  S3_BUCKET_NAME: main027-bucket

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
        run: 
          working-directory: ./server
    

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: write ADMIN EMAIL
      run: echo "ADMIN_EMAIL=${{secrets.ADMIN_EMAIL}}" >> env.yml
      working-directory: ./server/src/main/resources
    - name: write KEY
      run: echo "JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}}" >> env.yml
      working-directory: ./server/src/main/resources
    - name: access minute
      run: echo "ACCESS_TOKEN_EXPIRATION_MINUTE=${{secrets.ACCESS_TOKEN_EXPIRATION_MINUTE}}" >> env.yml
      working-directory: ./server/src/main/resources
    - name: refresh minute
      run: echo "REFRESH_TOKEN_EXPIRATION_MINUTE=${{secrets.REFRESH_TOKEN_EXPIRATION_MINUTE}}" >> env.yml
      working-directory: ./server/src/main/resources   
    - name: database username
      run: echo "MYSQL_DATABASE_USERNAME=${{secrets.MYSQL_DATABASE_USERNAME}}" >> env.yml
      working-directory: ./server/src/main/resources
    - name: database password
      run: echo "MYSQL_DATABASE_PASSWORD=${{secrets.MYSQL_DATABASE_PASSWORD}}" >> env.yml
      working-directory: ./server/src/main/resources
    - name: database url
      run: echo "MYSQL_DATABASE_URL=${{secrets.MYSQL_DATABASE_URL}}" >> env.yml
      working-directory: ./server/src/main/resources
    - name: mail username
      run: echo "MAIL_USERNAME=${{secrets.MAIL_USERNAME}}" >> env.yml
      working-directory: ./server/src/main/resources    
    - name: mail password
      run: echo "MAIL_PASSWORD=${{secrets.MAIL_PASSWORD}}" >> env.yml
      working-directory: ./server/src/main/resources    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
   # - name: Build with Gradle
   #   uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
   #   with:
   #     arguments: build
   
   # build한 후 프로젝트를 압축합니다.
    - name: Make zip file
      run: zip -r ./deploy.zip .
      shell: bash
    
    # Access Key와 Secret Access Key를 통해 권한을 확인합니다.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    
    # 압축한 프로젝트를 S3로 전송합니다.
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./deploy.zip s3://$S3_BUCKET_NAME/deploy.zip
    
    # CodeDeploy에게 배포 명령을 내립니다.
    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name main027
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name main027
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=deploy.zip
