name: backend branch test

on:
  push:
    branches: [ "backend" ]
  pull_request:
    branches:
    - 'backend'
    - 'dev'
    paths:
    - 'server/**'

permissions:
  contents: read
  
  
jobs:
  test:
    name: merge-test
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./server
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: write ADMIN EMAIL
      run: echo "ADMIN_EMAIL=${{secrets.ADMIN_EMAIL}}" >> env.yml
      working-directory: ./server/src/main/resources
    - name: write KEY
      run: echo "JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}}" >> env.yml
      working-directory: ./server/src/main/resources
    - name: access minute
      run: echo "ACCESS_TOKEN_EXPIRATION_MINUTE=${{secrets.ACCESS_TOKEN_EXPIRATION_MINUTE}}" >> env.yml
      working-directory: ./server/src/main/resources
    - name: refresh minute
      run: echo "REFRESH_TOKEN_EXPIRATION_MINUTE=${{secrets.REFRESH_TOKEN_EXPIRATION_MINUTE}}" >> env.yml
      working-directory: ./server/src/main/resources   
    - name: database username
      run: echo "MYSQL_DATABASE_USERNAME=${{secrets.MYSQL_DATABASE_USERNAME}}" >> env.yml
      working-directory: ./server/src/main/resources
    - name: database password
      run: echo "MYSQL_DATABASE_PASSWORD=${{secrets.MYSQL_DATABASE_PASSWORD}}" >> env.yml
      working-directory: ./server/src/main/resources
    - name: database url
      run: echo "MYSQL_DATABASE_URL=${{secrets.MYSQL_DATABASE_URL}}" >> env.yml
      working-directory: ./server/src/main/resources  
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew build
